version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
    command: server /data --console-address ":9001"
    volumes:
      - ./Ebook/cloud/data:/data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - ebook-networks
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-docker
    networks:
      - ebook-networks
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db:rw
  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes:
  #     - ./Ebook/cache:/data

  server:
    image: ebookservice:2807-slim
    restart: always
    ports:
      - 3600:3600
    volumes:
      - ./Ebook:/source/Ebook
      - ./start-server.sh:/sourcecode/start-server.sh
    entrypoint: ["/bin/sh"]
    command: /sourcecode/start-server.sh
    networks:
      - ebook-networks
    depends_on:
      - mongodb
      - minio

  workers:
    image: ebookservice:2807-slim
    restart: always
    container_name: worker-pdfs
    volumes:
      - ./Ebook:/source/Ebook
      - ./start-workers.sh:/sourcecode/start-workers.sh
      - ./vie.traineddata:/usr/share/tesseract-ocr/5/tessdata/vie.traineddata
    entrypoint: ["/bin/sh"]
    command: /sourcecode/start-workers.sh
    depends_on:
      - server
      - mongodb
      - minio
      - rabbit
    networks:
      - ebook-networks

  monitor:
    image: ebookservice:2807-slim
    restart: always
    container_name: monitor-flower
    volumes:
      - ./Ebook:/source/Ebook
      - ./start-monitor.sh:/sourcecode/start-monitor.sh
    entrypoint: ["/bin/sh"]
    ports:
      - 5555:5555
    command: /sourcecode/start-monitor.sh
    depends_on:
      - workers
    networks:
      - ebook-networks

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./queue-data:/var/lib/rabbitmq
    networks:
      - ebook-networks
    
volumes:
  cache:
    driver: local

networks:
  ebook-networks:
    driver: bridge