version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
    command: server /data --console-address ":9001"
    volumes:
      - ./Ebook/cloud/data:/data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./Ebook/cache:/data

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
# volumes:
#   cache:
#     driver: local
