FROM python:3.8-slim

COPY . /source 

RUN apt-get update && apt install -y git

RUN python -m pip install --upgrade pip
WORKDIR /source/Ebook
RUN cd /source/Ebook & pip install -r requirements.txt
####
# for audio processing
RUN apt-get -y install ffmpeg 
###
RUN apt-get -y install tesseract-ocr 
RUN apt-get -y install libtesseract-dev
