version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
